<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /Dedecms/uploads/uploads/allimg/161224/1-161224214217.jpg ",93,272);
$z[1][4]['ddimg']="/Dedecms/uploads/uploads/allimg/161224/1-161224214217.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="640";
$z[1][4]['height']="479";

?>