<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /Dedecms/uploads/uploads/allimg/161207/1-16120H04256.jpg ",93,270);
$z[1][4]['ddimg']="/Dedecms/uploads/uploads/allimg/161207/1-16120H04256.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="400";
$z[1][4]['height']="225";
$z[2]=Array("img"," /Dedecms/uploads/uploads/allimg/161207/1-16120H04259.jpg ",272,449);
$z[2][4]['ddimg']="/Dedecms/uploads/uploads/allimg/161207/1-16120H04259.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="400";
$z[2][4]['height']="225";
$z[3]=Array("img"," /Dedecms/uploads/uploads/allimg/161207/1-16120H04304.jpg ",451,628);
$z[3][4]['ddimg']="/Dedecms/uploads/uploads/allimg/161207/1-16120H04304.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="400";
$z[3][4]['height']="225";

?>