<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /Dedecms/uploads/uploads/allimg/170418/1-1F41Q33103.jpg ",93,268);
$z[1][4]['ddimg']="/Dedecms/uploads/uploads/allimg/170418/1-1F41Q33103.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="172";
$z[1][4]['height']="120";
$z[2]=Array("img"," /Dedecms/uploads/uploads/allimg/170418/1-1F41Q33107.jpg ",270,445);
$z[2][4]['ddimg']="/Dedecms/uploads/uploads/allimg/170418/1-1F41Q33107.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="172";
$z[2][4]['height']="120";
$z[3]=Array("img"," /Dedecms/uploads/uploads/allimg/170418/1-1F41Q33112.jpg ",447,622);
$z[3][4]['ddimg']="/Dedecms/uploads/uploads/allimg/170418/1-1F41Q33112.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="172";
$z[3][4]['height']="120";

?>