<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /Dedecms/uploads/uploads/allimg/161223/1-161223215315.jpg ",93,272);
$z[1][4]['ddimg']="/Dedecms/uploads/uploads/allimg/161223/1-161223215315.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="955";
$z[1][4]['height']="598";
$z[2]=Array("img"," /Dedecms/uploads/uploads/allimg/161223/1-161223215320.jpg ",274,453);
$z[2][4]['ddimg']="/Dedecms/uploads/uploads/allimg/161223/1-161223215320.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="901";
$z[2][4]['height']="598";
$z[3]=Array("img"," /Dedecms/uploads/uploads/allimg/161223/1-161223215323.jpg ",455,634);
$z[3][4]['ddimg']="/Dedecms/uploads/uploads/allimg/161223/1-161223215323.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="978";
$z[3][4]['height']="560";

?>