<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'54Ot54K55paw6Ze7');
$cfg_Cs[2]=array(0,2,1,'5Zu+6ZuG5Zu+6ZuG');
$cfg_Cs[3]=array(0,6,1,'6IGa5a6e5oOg');
$cfg_Cs[4]=array(0,2,1,'5oqi57qi5YyF');
$cfg_Cs[5]=array(0,2,1,'57KJ5Lid57uP5rWO');
$cfg_Cs[6]=array(0,2,1,'5oi/5Lqn');
$cfg_Cs[7]=array(0,2,1,'5oub6IGY');
$cfg_Cs[8]=array(0,6,1,'5rG96L2m');
$cfg_Cs[9]=array(0,2,1,'576O5a65');
$cfg_Cs[10]=array(0,2,1,'6auY5a6J56S+5Yy6');
$cfg_Cs[12]=array(3,6,1,'5pWZ6IKy');
$cfg_Cs[14]=array(0,2,1,'5bm/5ZGK');
$cfg_Cs[15]=array(3,6,1,'5Yac5Lqn5ZOB');
?>